package model;

public enum SpecialityEnum {
    ENDODONTICS,
    ORTHODONTICS,
    PERIODONTICS,
    PROSTHODONTICS,
    ORAL_SURGERY,
    PEDIATRIC_DENTISTRY,
    ORAL_PATHOLOGY,
    ORAL_MEDICINE,
    ORAL_RADIOLGY,
    DENTAL_PUBLIC_HEALTH
}
