/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import java.awt.Color;
import java.awt.event.MouseEvent;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

import exceptions.DuplicateException;
import exceptions.ValueNotFoundException;
import model.Doctor;
import model.MedicalPractice;
import persistence.Persistence;

/**
 * @author Samir
 */
public class CreateDoc extends javax.swing.JPanel {
    private static final String PATHDOCTOR = "src\\persistence\\resources\\outputData\\Doctors.txt";
    private static MedicalPractice medicalPractice = new MedicalPractice();

    /**
     * Creates new form CreateDoc
     */
    public CreateDoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        bg = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        tfname = new javax.swing.JTextField();
        lastName = new javax.swing.JLabel();
        tflastName = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        tfphone = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        tfaddress = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        specialty = new javax.swing.JLabel();
        tfspecialty = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));

        message.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        message.setText("Create a Doctor");

        id.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        id.setText("Id");

        tfid.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        tfid.setForeground(new java.awt.Color(153, 153, 153));
        tfid.setText("Enter Your id");

        tfname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfidMousePressed(evt);
            }
        });

        name.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        name.setText("Name");

        tfname.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        tfname.setForeground(new java.awt.Color(153, 153, 153));
        tfname.setText("Enter Your Name");
        tfname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfnameMousePressed(evt);
            }
        });

        lastName.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lastName.setText("Last Name");

        tflastName.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        tflastName.setForeground(new java.awt.Color(153, 153, 153));
        tflastName.setText("Enter Your Last Name");
        tflastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tflastNameMousePressed(evt);
            }
        });

        phone.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        phone.setText("Phone");

        tfphone.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        tfphone.setForeground(new java.awt.Color(153, 153, 153));
        tfphone.setText("Enter Your Phone");
        tfphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfphoneMousePressed(evt);
            }
        });

        address.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        address.setText("Address");

        tfaddress.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        tfaddress.setForeground(new java.awt.Color(153, 153, 153));
        tfaddress.setText("Enter Your Address");
        tfaddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfaddressMousePressed(evt);
            }
        });

        email.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        email.setText("Email");

        tfemail.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        tfemail.setForeground(new java.awt.Color(153, 153, 153));
        tfemail.setText("Enter Your Email");
        tfemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfemailMousePressed(evt);
            }
        });

        specialty.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        specialty.setText("Specialty");

        tfspecialty.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        tfspecialty.setForeground(new java.awt.Color(153, 153, 153));
        tfspecialty.setText("Enter Your Specialty");
        tfspecialty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfspecialtyMousePressed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnSend.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        btnSend.setText("Send");
        btnSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel1.setText(
                "- Welcome, we are glad to add a new professional to our work team, please enter the Doctor's information");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgLayout.createSequentialGroup().addGap(30, 30, 30).addComponent(message))
                .addGroup(bgLayout.createSequentialGroup().addGap(440, 440, 440).addComponent(btnSend,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgLayout.createSequentialGroup().addGap(50, 50, 50).addGroup(bgLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(name)
                                        .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastName)
                                        .addComponent(tflastName, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phone).addComponent(tfphone,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70,
                                        70)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(address)
                                        .addComponent(tfaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(email)
                                        .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(specialty).addComponent(tfspecialty,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))))));
        bgLayout.setVerticalGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgLayout.createSequentialGroup().addGap(50, 50, 50).addComponent(message).addGap(18, 18, 18)
                        .addComponent(jLabel1).addGap(31, 31, 31)
                        .addGroup(bgLayout
                                .createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(bgLayout.createSequentialGroup().addComponent(name).addGap(8, 8, 8)
                                        .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tflastName, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6).addComponent(tfphone, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bgLayout.createSequentialGroup().addGap(10, 10, 10).addComponent(jSeparator2,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 260,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bgLayout.createSequentialGroup().addComponent(address).addGap(8, 8, 8)
                                        .addComponent(tfaddress, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(specialty, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6).addComponent(tfspecialty,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80).addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                javax.swing.GroupLayout.PREFERRED_SIZE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(bg,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(bg,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {
        // ADICIONAR DOCTOR A MEDICAL PRACTICE obtiendo los datos de los labels
        // Obtener los valores de los JTextField
        try {
            String idText = tfid.getText();
            int id = Integer.parseInt(idText);
            String name = tfname.getText();
            String lastName = tflastName.getText();
            String phone = tfphone.getText();
            String address = tfaddress.getText();
            String email = tfemail.getText();
            // String speciality=tfemail.get;
            // Validar los campos obligatorios
            if (name.isEmpty() || lastName.isEmpty() || phone.isEmpty() || address.isEmpty() || email.isEmpty()
                    || idText.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill in all the fields");
                return;
            }

            if (medicalPractice.findDoctor(id) == -1) {
                Doctor doctor = new Doctor();
                doctor.setId(id);
                doctor.setName(name);
                doctor.setLastName(lastName);
                doctor.setPhone(phone);
                doctor.setAddress(address);
                doctor.setEmail(email);
                // doctor.setSpeciality();
                medicalPractice.addDoctor(doctor);
                Persistence.writeFile(medicalPractice.getPatients().toString(), PATHDOCTOR);
                JOptionPane.showMessageDialog(null, "Doctor created successfully");
            } else {
                Exception e = new DuplicateException("This doctor already exists");
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } catch (Exception em) {
            Exception e = new ValueNotFoundException("This doctor already exists");
            JOptionPane.showMessageDialog(null, em.getMessage());
        }

    }

    private void tfnameMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if (tfname.getText().equals("Enter Your Name")) {
            tfname.setText("");
            tfname.setForeground(Color.BLACK);
        }
    }

    private void tfidMousePressed(MouseEvent evt) {
        if (tfid.getText().equals("Enter the Id")) {
            tfid.setText("");
            tfid.setForeground(Color.BLACK);
        }

    }

    private void tflastNameMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if (tflastName.getText().equals("Enter Your Last Name")) {
            tflastName.setText("");
            tflastName.setForeground(Color.BLACK);
        }
    }

    private void tfphoneMousePressed(java.awt.event.MouseEvent evt) {
        if (tfphone.getText().equals("Enter Your Phone")) {
            tfphone.setText("");
            tfphone.setForeground(Color.BLACK);
        } // TODO add your handling code here:
    }

    private void tfaddressMousePressed(java.awt.event.MouseEvent evt) {
        if (tfaddress.getText().equals("Enter Your Address")) {
            tfaddress.setText("");
            tfaddress.setForeground(Color.BLACK);
        } // TODO add your handling code here:
    }

    private void tfemailMousePressed(java.awt.event.MouseEvent evt) {
        if (tfemail.getText().equals("Enter Your Email")) {
            tfemail.setText("");
            tfemail.setForeground(Color.BLACK);
        } // TODO add your handling code here:
    }

    private void tfspecialtyMousePressed(java.awt.event.MouseEvent evt) {
        if (tfspecialty.getText().equals("Enter Your Specialty")) {
            tfspecialty.setText("");
            tfspecialty.setForeground(Color.BLACK);
        } // TODO add your handling code here:
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel address;
    private javax.swing.JLabel id;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel message;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel specialty;
    private javax.swing.JTextField tfaddress;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tflastName;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfphone;
    private javax.swing.JTextField tfspecialty;
    // End of variables declaration
}
